window.TRANSLATED_EXTENDED_DRIVER_QA = {
  es: [
    { q: "¿Qué significa una luz amarilla fija del semáforo?", a: "Que la luz está por ponerse roja; deténgase de forma segura si puede." },
    { q: "¿Qué significa una flecha verde en una intersección?", a: "Puede girar en la dirección de la flecha, cediendo el paso al tránsito cruzado legal." },
    { q: "¿Qué significa una doble línea amarilla continua al centro?", a: "Prohibido rebasar en ambos sentidos." },
    { q: "¿Qué significa una línea blanca discontinua entre carriles?", a: "Se permiten cambios de carril cuando sea seguro." },
    { q: "¿Cuándo debe revisar el punto ciego?", a: "Antes de cada cambio de carril y de incorporarse." },
    { q: "¿Cuál es la forma más segura de incorporarse a una autopista?", a: "Use el carril de aceleración, iguale la velocidad del tráfico y luego incorpórese cuando haya espacio." },
    { q: "Si se pasa de su salida, ¿qué debe hacer?", a: "Continúe hasta la siguiente salida y reoriente su ruta con seguridad." },
    { q: "¿Qué debe hacer en una parada de cuatro vías?", a: "Pasa primero el primer vehículo que se detuvo; si empatan, ceda al vehículo de su derecha." },
    { q: "¿Quién tiene el derecho de paso al entrar desde una entrada privada?", a: "El tráfico que ya circula por la vía y los peatones en la acera." },
    { q: "¿Qué debe hacer antes de retroceder?", a: "Revise todos los espejos, mire por encima del hombro y muévase lentamente." },
    { q: "¿Por qué es peligroso seguir a otro vehículo muy de cerca?", a: "Deja muy poca distancia de frenado y aumenta el riesgo de choque por alcance." },
    { q: "¿Cuándo debe aumentar la distancia de seguimiento más allá de 3 segundos?", a: "Con lluvia, niebla, nieve, oscuridad, tráfico denso o al remolcar." },
    { q: "¿Qué significa hidroplaneo?", a: "Que los neumáticos pierden contacto con la carretera por el agua." },
    { q: "¿Qué debe hacer si su vehículo empieza a hidroplanear?", a: "Suelte suavemente el acelerador, mantenga el volante recto y evite frenar bruscamente." },
    { q: "¿Cuál es la velocidad más segura en niebla?", a: "Una velocidad reducida que le permita detenerse dentro de la distancia visible." },
    { q: "Al usar luces altas, ¿cuándo debe bajarlas?", a: "Al acercarse a tráfico de frente o al seguir de cerca a otro vehículo." },
    { q: "¿Qué debe hacer si fallan los faros de noche?", a: "Encienda las intermitentes, reduzca la velocidad y salga de la vía con seguridad." },
    { q: "Si revienta una llanta, ¿cuál es la primera respuesta?", a: "Sujete el volante con firmeza, suelte el acelerador y mantenga la dirección recta hasta controlar el vehículo." },
    { q: "¿Qué indica normalmente una banqueta pintada de rojo?", a: "Prohibido detenerse, permanecer parado o estacionarse." },
    { q: "¿Qué indica normalmente una banqueta pintada de azul?", a: "Estacionamiento reservado para personas con permiso de discapacidad." },
    { q: "¿Qué debe hacer antes de abrir la puerta del auto estacionado hacia el tráfico?", a: "Revise espejos y mire por encima del hombro por ciclistas y vehículos." },
    { q: "Al estacionarse en paralelo, ¿qué tan cerca debe quedar de la banqueta?", a: "Lo suficientemente cerca para no obstruir el tráfico, normalmente dentro de una corta distancia legal." },
    { q: "Al estacionar cuesta abajo con banqueta, las ruedas deben apuntar:", a: "Hacia la banqueta." },
    { q: "Al estacionar cuesta arriba sin banqueta, las ruedas deben apuntar:", a: "Hacia el borde de la vía." },
    { q: "¿Qué debe hacer cuando se acerca una ambulancia con luces y sirena?", a: "Ceda el paso, muévase a la derecha y deténgase cuando sea seguro." },
    { q: "¿Puede entrar a una intersección si va a quedar bloqueándola?", a: "No; no entre a menos que pueda despejarla." },
    { q: "¿Cuál es una señal común de conducción agresiva?", a: "Exceso de velocidad, zigzaguear, seguir de cerca o cambios de carril inseguros frecuentes." },
    { q: "¿Cómo debe responder ante un conductor agresivo?", a: "No se involucre; cree espacio y déjelo pasar." },
    { q: "¿Por qué ambas manos deben estar disponibles en el volante?", a: "Mejora el control y la reacción en emergencias." },
    { q: "¿Qué debe hacer antes de girar a la izquierda cruzando tráfico?", a: "Ceda a vehículos de frente y peatones, y gire solo cuando esté libre." },
    { q: "¿Qué indica una señal de cruce ferroviario en forma de cruz (crossbuck)?", a: "Que hay un cruce de ferrocarril adelante; prepárese para detenerse." },
    { q: "¿Cuándo debe detenerse en las vías del tren?", a: "Cuando destellan señales, están bajas las barreras, se ve un tren o lo exige la ley." },
    { q: "Si su vehículo se apaga sobre las vías del tren, ¿qué debe hacer?", a: "Salga de inmediato y aléjese de las vías; llame a emergencias." },
    { q: "¿Cuál es la forma más segura de controlar la velocidad en bajadas largas?", a: "Use una marcha baja y frenado controlado, no presión fuerte continua del freno." },
    { q: "¿Por qué las zonas de obra son de alto riesgo?", a: "Por desvíos de carril, trabajadores cerca, menos espacio y frenadas repentinas." },
    { q: "¿Cómo debe conducir en una zona de obra?", a: "Reduzca la velocidad, siga señales, mantenga mayor distancia y evite distracciones." },
    { q: "¿Qué implica una señal de zona escolar?", a: "Velocidad reducida y mayor precaución por peatones cuando está activa." },
    { q: "¿Cuándo es obligatorio el cinturón de seguridad?", a: "Para conductores y pasajeros según la ley estatal; la práctica más segura es siempre usarlo." },
    { q: "¿Por qué los niños deben usar asiento infantil/elevador adecuado?", a: "Porque brinda un ajuste correcto de sujeción y reduce el riesgo de lesiones." },
    { q: "¿Cuál es el riesgo de conducir con sueño?", a: "Juicio deteriorado y reacción tardía, similar a la intoxicación." },
    { q: "¿Qué debe hacer si siente somnolencia al conducir?", a: "Deténgase en un lugar seguro y descanse antes de continuar." },
    { q: "¿Pueden los medicamentos afectar la capacidad de conducir?", a: "Sí; algunos reducen alerta, coordinación o juicio." },
    { q: "¿Qué relación hay entre la edad legal para beber y los límites de DUI?", a: "Los conductores menores suelen tener límites de alcohol en sangre de tolerancia cero o muy bajos." },
    { q: "¿Qué es el consentimiento implícito en la ley de DUI?", a: "Al conducir, usted consiente pruebas químicas legales; negarse trae sanciones." },
    { q: "¿Qué debe hacer si no funcionan los semáforos?", a: "Trate la intersección como una parada de todas las vías y avance con cuidado." },
    { q: "¿Qué significa una señal de control de carril con flechas?", a: "Que desde ese carril solo se permiten ciertos movimientos." },
    { q: "¿Cómo debe posicionar su vehículo para girar a la derecha?", a: "Aproxímese por el carril más a la derecha posible y gire al carril más cercano cuando sea legal." },
    { q: "¿Cómo debe posicionar su vehículo para girar a la izquierda en una vía de doble sentido?", a: "Aproxímese cerca de la línea central y gire al carril correspondiente cuando esté libre." },
    { q: "Al rebasar a un ciclista, ¿cuál es la regla segura?", a: "Deje amplio espacio y pase solo cuando sea legal y seguro." },
    { q: "¿Quién es más vulnerable en el tráfico?", a: "Peatones, ciclistas y motociclistas." },
    { q: "¿Por qué debe evitar detenerse en los cruces peatonales?", a: "Porque bloquea el derecho de paso y la visibilidad de los peatones." },
    { q: "¿Qué suele significar una señal triangular roja y blanca?", a: "Ceda el paso." },
    { q: "¿Qué suele indicar una señal vial con forma de pentágono?", a: "Zona escolar o cruce escolar." },
    { q: "¿Qué debe hacer antes de entrar a una rotonda?", a: "Ceder el paso al tráfico que ya circula en la rotonda." },
    { q: "¿Cómo debe señalizar en una rotonda?", a: "Señalice su salida cuando se prepare para salir." },
    { q: "¿Cuál es el propósito de los frenos ABS?", a: "Ayudan a mantener el control de dirección durante una frenada fuerte." },
    { q: "¿Cómo debe frenar con ABS?", a: "Presione firme y mantenga; no bombee repetidamente." },
    { q: "¿Qué debe hacer si se atora el acelerador?", a: "Ponga en neutral, dirija con seguridad y frene hasta detenerse de forma controlada." },
    { q: "Tras una colisión menor sin heridos, ¿cuál es la prioridad?", a: "Moverse a un lugar seguro si es posible e intercambiar la información requerida." },
    { q: "¿Qué documentos debe portar normalmente un conductor?", a: "Licencia vigente, registro del vehículo y comprobante de seguro." },
    { q: "¿Qué es la conducción defensiva?", a: "Anticipar peligros y tomar decisiones seguras y legales para prevenir choques." },
    { q: "¿Por qué deben ajustarse los espejos antes de conducir?", a: "Para reducir puntos ciegos y mejorar la percepción del entorno." },
    { q: "¿Cuándo deben usarse las luces intermitentes de emergencia?", a: "En emergencias o para advertir vehículo averiado, no en conducción rutinaria." },
    { q: "¿Qué debe hacer en una intersección sin control?", a: "Reduzca la velocidad, ceda cuando sea necesario y avance solo cuando sea seguro." },
    { q: "¿Qué significa una marca de zona de no rebase?", a: "No cruce al carril contrario para rebasar." },
    { q: "¿Cómo manejar una línea amarilla con un lado discontinuo y otro continuo?", a: "Solo el lado con línea discontinua puede rebasar cuando sea seguro." },
    { q: "¿Cuál es el hábito más seguro en luz verde?", a: "Mirar izquierda-derecha-izquierda antes de entrar a la intersección." },
    { q: "¿Por qué la velocidad debe ajustarse a las condiciones y no solo al límite?", a: "Los límites legales suponen condiciones ideales; clima y tráfico pueden exigir menor velocidad." },
    { q: "¿Qué es disciplina de carril?", a: "Permanecer en su carril y cambiar solo cuando sea necesario y seguro." },
    { q: "¿Cómo debe reaccionar ante un derrape en hielo?", a: "Mire hacia donde quiere ir y gire suavemente en esa dirección." },
    { q: "¿Qué hacer si otro conductor tiene direccional encendida pero no se mueve?", a: "No suponga su intención; espere movimiento real y un hueco seguro." },
    { q: "¿Qué significa en la práctica el derecho de paso?", a: "La prioridad legal para avanzar primero, pero nunca imponerla de forma insegura." },
    { q: "¿Por qué es inseguro depender solo del GPS?", a: "Las señales, condiciones y normas legales pueden prevalecer sobre la ruta indicada." },
    { q: "¿Cuál es una regla clave cerca de peatones de noche?", a: "Reduzca velocidad y esté listo para detenerse de inmediato." },
    { q: "¿Cómo debe pasar junto a vehículos de emergencia o servicio estacionados cuando la ley lo exige?", a: "Cambie de carril si es seguro o reduzca considerablemente la velocidad si no puede cambiar de carril." }
  ],
  uk: [
    { q: "Що означає постійний жовтий сигнал світлофора?", a: "Світло незабаром стане червоним; безпечно зупиніться, якщо можете." },
    { q: "Що означає зелена стрілка на перехресті?", a: "Можна повертати у напрямку стрілки, надаючи перевагу законному перехресному руху." },
    { q: "Що означає подвійна суцільна жовта лінія по центру?", a: "Обгін заборонений в обох напрямках." },
    { q: "Що означає переривчаста біла лінія між смугами?", a: "Зміна смуги дозволена, коли це безпечно." },
    { q: "Коли слід перевіряти «сліпу зону»?", a: "Перед кожною зміною смуги та злиттям у потік." },
    { q: "Який найбезпечніший спосіб влитися на автомагістраль?", a: "Використати смугу розгону, зрівняти швидкість з потоком і влитися, коли є проміжок." },
    { q: "Якщо ви пропустили свій з’їзд, що робити?", a: "Їдьте до наступного з’їзду та безпечно скоригуйте маршрут." },
    { q: "Що робити на перехресті з чотирма знаками STOP?", a: "Першим їде той, хто першим зупинився; при одночасній зупинці поступіться авто праворуч." },
    { q: "Хто має перевагу при виїзді з приватного заїзду?", a: "Транспорт на дорозі та пішоходи на тротуарі." },
    { q: "Що зробити перед рухом заднім ходом?", a: "Перевірити всі дзеркала, подивитися через плече та рухатися повільно." },
    { q: "Чому небезпечно «сісти на хвіст»?", a: "Залишається надто мала дистанція для зупинки, зростає ризик наїзду ззаду." },
    { q: "Коли потрібно збільшувати дистанцію понад 3 секунди?", a: "Під час дощу, туману, снігу, у темряві, щільному трафіку або при буксируванні." },
    { q: "Що таке аквапланування?", a: "Коли шини втрачають контакт із дорогою через воду." },
    { q: "Що робити, якщо авто почало аквапланувати?", a: "Плавно відпустити газ, тримати кермо прямо та уникати різкого гальмування." },
    { q: "Яка найбезпечніша швидкість у тумані?", a: "Знижена швидкість, що дозволяє зупинитися в межах видимої відстані." },
    { q: "Коли слід перемикати дальнє світло на ближнє?", a: "Коли наближаєтесь до зустрічного транспорту або їдете близько за іншим авто." },
    { q: "Що робити, якщо вночі відмовили фари?", a: "Увімкнути аварійку, зменшити швидкість і безпечно з’їхати з дороги." },
    { q: "Якщо лопнула шина, яка перша дія?", a: "Міцно тримайте кермо, відпустіть газ і тримайте прямий курс, доки не відновите контроль." },
    { q: "Що зазвичай означає червоний бордюр?", a: "Зупинка, стоянка та паркування заборонені." },
    { q: "Що зазвичай означає синій бордюр?", a: "Паркування лише для власників дозволу для осіб з інвалідністю." },
    { q: "Що зробити перед відкриттям дверей припаркованого авто в бік руху?", a: "Перевірити дзеркала і подивитися через плече на велосипедистів та авто." },
    { q: "Під час паралельного паркування наскільки близько ставати до бордюру?", a: "Достатньо близько, щоб не заважати руху, зазвичай у межах короткої законної відстані." },
    { q: "Під час паркування вниз схилом з бордюром колеса мають бути повернуті:", a: "До бордюру." },
    { q: "Під час паркування вгору схилом без бордюру колеса мають бути повернуті:", a: "До краю дороги." },
    { q: "Що робити, коли під’їжджає швидка з маячками та сиреною?", a: "Надати перевагу, зміститися праворуч і зупинитися, коли це безпечно." },
    { q: "Чи можна заїжджати на перехрестя, якщо ви його заблокуєте?", a: "Ні; не в’їжджайте, якщо не можете повністю його звільнити." },
    { q: "Яка поширена ознака агресивного водіння?", a: "Надмірна швидкість, «плетіння» між смугами, їзда впритул або часті небезпечні перебудови." },
    { q: "Як реагувати на агресивного водія?", a: "Не вступайте у конфлікт; збільшіть дистанцію і дайте йому проїхати." },
    { q: "Чому обидві руки мають бути доступні на кермі?", a: "Це покращує контроль і реакцію в екстрених ситуаціях." },
    { q: "Що зробити перед лівим поворотом через зустрічний рух?", a: "Дати дорогу зустрічним авто та пішоходам, повертати лише коли вільно." },
    { q: "Що означає знак залізничного переїзду (хрест)?", a: "Попереду залізничний переїзд; будьте готові зупинитися." },
    { q: "Коли обов’язково зупинятися перед залізничними коліями?", a: "Коли блимають сигнали, опущений шлагбаум, видно потяг або це вимагає закон." },
    { q: "Якщо авто заглухло на коліях, що робити?", a: "Негайно вийти і відійти від колій; викликати екстрені служби." },
    { q: "Як найбезпечніше утримувати швидкість на довгих спусках?", a: "Використовувати нижчу передачу і контрольоване гальмування, а не постійний сильний тиск на гальма." },
    { q: "Чому зони дорожніх робіт мають високий ризик?", a: "Зміни смуг, працівники поруч, менше простору та раптові уповільнення." },
    { q: "Як слід їхати в зоні дорожніх робіт?", a: "Зменшити швидкість, дотримуватися знаків, тримати більшу дистанцію й уникати відволікань." },
    { q: "Що означає знак шкільної зони?", a: "Знижену швидкість і підвищену обережність щодо пішоходів, коли зона активна." },
    { q: "Коли ремені безпеки є обов’язковими?", a: "Для водія і пасажирів згідно із законом штату; найбезпечніше користуватися завжди." },
    { q: "Чому діти мають використовувати належні автокрісла/бустери?", a: "Вони забезпечують правильну фіксацію та зменшують ризик травм." },
    { q: "Який ризик керування в сонному стані?", a: "Погіршене мислення і сповільнена реакція, подібно до сп’яніння." },
    { q: "Що робити, якщо під час керування відчуваєте сонливість?", a: "Безпечно зупиніться і відпочиньте перед продовженням поїздки." },
    { q: "Чи можуть ліки впливати на здатність керувати?", a: "Так; деякі знижують пильність, координацію або здатність оцінювати ситуацію." },
    { q: "Який зв’язок між законним віком вживання алкоголю і межами DUI?", a: "Для неповнолітніх водіїв часто діють суворіші межі BAC нульової/низької толерантності." },
    { q: "Що таке «непряма згода» у законах про DUI?", a: "Керуючи авто, ви погоджуєтесь на законні хімічні тести; відмова тягне покарання." },
    { q: "Що робити, якщо світлофори не працюють?", a: "Сприймайте перехрестя як STOP з усіх напрямків і рухайтеся обережно." },
    { q: "Що означає знак використання смуги зі стрілками?", a: "Із цієї смуги дозволені лише певні маневри." },
    { q: "Як розташувати авто для правого повороту?", a: "Під’їжджайте в крайній правій практичній смузі та повертайте в найближчу смугу, коли це законно." },
    { q: "Як розташувати авто для лівого повороту на двосторонній дорозі?", a: "Під’їжджайте ближче до осьової лінії і повертайте у відповідну смугу, коли вільно." },
    { q: "Яке безпечне правило під час обгону велосипедиста?", a: "Залишайте достатній боковий інтервал і обганяйте лише коли це законно та безпечно." },
    { q: "Хто найбільш вразливий у дорожньому русі?", a: "Пішоходи, велосипедисти та мотоциклісти." },
    { q: "Чому не можна зупинятися на пішохідних переходах?", a: "Це блокує право пішоходів і погіршує оглядовість." },
    { q: "Що зазвичай означає трикутний червоно-білий знак?", a: "Дати дорогу." },
    { q: "Що зазвичай означає дорожній знак у формі п’ятикутника?", a: "Шкільна зона або шкільний перехід." },
    { q: "Що зробити перед в’їздом на круговий рух?", a: "Дати дорогу транспорту, який уже рухається по кільцю." },
    { q: "Як подавати сигнал на круговому русі?", a: "Увімкнути сигнал виїзду, готуючись залишити кільце." },
    { q: "Для чого потрібні гальма ABS?", a: "Вони допомагають зберегти керованість під час інтенсивного гальмування." },
    { q: "Як гальмувати з ABS?", a: "Натисніть сильно і утримуйте; не «качайте» педаль багаторазово." },
    { q: "Що робити, якщо заклинив акселератор?", a: "Перемкнути на нейтраль, безпечно керувати і гальмувати до контрольованої зупинки." },
    { q: "Після незначної ДТП без постраждалих що в пріоритеті?", a: "За можливості переміститися в безпечне місце та обмінятися необхідною інформацією." },
    { q: "Які документи водій зазвичай повинен мати при собі?", a: "Дійсне посвідчення водія, реєстрацію авто та підтвердження страхування." },
    { q: "Що таке захисне (оборонне) водіння?", a: "Передбачення небезпек і прийняття безпечних, законних рішень для запобігання ДТП." },
    { q: "Чому дзеркала треба налаштувати до початку руху?", a: "Щоб зменшити сліпі зони і підвищити обізнаність про оточення." },
    { q: "Коли слід використовувати аварійну сигналізацію?", a: "У разі аварійної ситуації або поломки, а не для звичайного руху." },
    { q: "Що робити на нерегульованому перехресті?", a: "Знизити швидкість, за потреби надати перевагу та їхати лише коли безпечно." },
    { q: "Що означає розмітка зони заборони обгону?", a: "Не виїжджати на зустрічну смугу для обгону." },
    { q: "Як діяти при жовтій лінії, де з одного боку переривчаста, а з іншого суцільна?", a: "Обганяти може лише сторона з переривчастою лінією, коли це безпечно." },
    { q: "Яка найбезпечніша звичка на зеленому сигналі?", a: "Подивитися ліворуч-праворуч-ліворуч перед в’їздом на перехрестя." },
    { q: "Чому швидкість слід підбирати за умовами, а не лише за лімітом?", a: "Ліміт передбачає ідеальні умови; погода й трафік можуть вимагати меншої швидкості." },
    { q: "Що таке дисципліна смуги?", a: "Триматися своєї смуги і змінювати її лише за потреби та безпечно." },
    { q: "Як реагувати на занос на льоду?", a: "Дивіться туди, куди хочете їхати, і м’яко керуйте в тому напрямку." },
    { q: "Що робити, якщо інший водій увімкнув поворотник, але не рухається?", a: "Не покладайтеся на припущення; чекайте фактичного руху і безпечного проміжку." },
    { q: "Що означає перевага руху на практиці?", a: "Законний пріоритет проїзду першим, але ніколи не «виборюйте» його небезпечно." },
    { q: "Чому небезпечно покладатися лише на GPS?", a: "Дорожні знаки, умови і правила можуть мати пріоритет над навігацією." },
    { q: "Яке ключове правило біля пішоходів уночі?", a: "Знизити швидкість і бути готовим негайно зупинитися." },
    { q: "Як проїжджати повз припарковані аварійні або сервісні авто, коли цього вимагає закон?", a: "Безпечно перестройтесь у сусідню смугу або суттєво зменште швидкість, якщо перестроїтися неможливо." }
  ],
  ru: [
    { q: "Что означает постоянный желтый сигнал светофора?", a: "Скоро загорится красный; безопасно остановитесь, если можете." },
    { q: "Что означает зеленая стрелка на перекрестке?", a: "Можно поворачивать по направлению стрелки, уступая законному поперечному движению." },
    { q: "Что означает двойная сплошная желтая линия по центру?", a: "Обгон запрещен в обоих направлениях." },
    { q: "Что означает прерывистая белая линия между полосами?", a: "Перестроение разрешено, если это безопасно." },
    { q: "Когда нужно проверять слепую зону?", a: "Перед каждым перестроением и слиянием с потоком." },
    { q: "Как безопаснее всего вливаться на автомагистраль?", a: "Используйте разгонную полосу, сравняйте скорость с потоком и вливайтесь при наличии промежутка." },
    { q: "Если вы пропустили свой съезд, что делать?", a: "Езжайте до следующего съезда и безопасно перестройте маршрут." },
    { q: "Что делать на перекрестке с четырехсторонним STOP?", a: "Первым едет тот, кто первым остановился; при одновременной остановке уступите автомобилю справа." },
    { q: "Кто имеет преимущество при выезде с частного въезда?", a: "Транспорт на дороге и пешеходы на тротуаре." },
    { q: "Что нужно сделать перед движением задним ходом?", a: "Проверить все зеркала, посмотреть через плечо и двигаться медленно." },
    { q: "Почему опасно ехать вплотную к впереди идущему авто?", a: "Слишком мало дистанции для остановки, повышается риск наезда сзади." },
    { q: "Когда следует увеличивать дистанцию более 3 секунд?", a: "В дождь, туман, снег, темноту, плотный трафик или при буксировке." },
    { q: "Что такое аквапланирование?", a: "Шины теряют контакт с дорогой из-за слоя воды." },
    { q: "Что делать, если автомобиль начал аквапланировать?", a: "Плавно отпустите газ, держите руль прямо и избегайте резкого торможения." },
    { q: "Какая скорость в тумане наиболее безопасна?", a: "Пониженная скорость, позволяющая остановиться в пределах видимости." },
    { q: "Когда при дальнем свете нужно переключаться на ближний?", a: "При приближении встречного транспорта или при близком следовании за другим авто." },
    { q: "Что делать, если ночью отказали фары?", a: "Включить аварийку, снизить скорость и безопасно съехать с дороги." },
    { q: "Если лопнула шина, какая первая реакция?", a: "Крепко держите руль, отпустите газ и удерживайте прямое направление до восстановления контроля." },
    { q: "Что обычно означает красный бордюр?", a: "Остановка, стоянка и парковка запрещены." },
    { q: "Что обычно означает синий бордюр?", a: "Парковка только для владельцев разрешения для людей с инвалидностью." },
    { q: "Что сделать перед открытием двери припаркованного авто в сторону движения?", a: "Проверить зеркала и посмотреть через плечо на велосипедистов и автомобили." },
    { q: "При параллельной парковке насколько близко нужно встать к бордюру?", a: "Достаточно близко, чтобы не мешать движению, обычно в пределах небольшой законной дистанции." },
    { q: "При парковке под уклон с бордюром колеса должны быть направлены:", a: "К бордюру." },
    { q: "При парковке в гору без бордюра колеса должны быть направлены:", a: "К краю дороги." },
    { q: "Что делать, когда приближается скорая с маячками и сиреной?", a: "Уступить дорогу, сместиться вправо и остановиться, когда это безопасно." },
    { q: "Можно ли въезжать на перекресток, если вы его заблокируете?", a: "Нет; не въезжайте, если не можете полностью его освободить." },
    { q: "Какой распространенный признак агрессивного вождения?", a: "Чрезмерная скорость, «шашки», движение вплотную или частые небезопасные перестроения." },
    { q: "Как реагировать на агрессивного водителя?", a: "Не вступать в конфликт; увеличить дистанцию и дать ему проехать." },
    { q: "Почему обе руки должны быть доступны на руле?", a: "Это улучшает контроль и реакцию в экстренных ситуациях." },
    { q: "Что сделать перед левым поворотом через встречный поток?", a: "Уступить встречным авто и пешеходам, затем поворачивать, когда путь свободен." },
    { q: "Что обозначает железнодорожный знак-крест (crossbuck)?", a: "Впереди железнодорожный переезд; будьте готовы остановиться." },
    { q: "Когда нужно останавливаться у железнодорожных путей?", a: "Когда мигают сигналы, опущены шлагбаумы, виден поезд или этого требует закон." },
    { q: "Если автомобиль заглох на путях, что делать?", a: "Немедленно выйти из машины и отойти от путей; вызвать экстренные службы." },
    { q: "Как безопаснее всего удерживать скорость на длинных спусках?", a: "Использовать пониженную передачу и контролируемое торможение, а не постоянное сильное нажатие на тормоз." },
    { q: "Почему зоны дорожных работ опасны?", a: "Смещение полос, рабочие рядом, меньше пространства и внезапные замедления." },
    { q: "Как следует ехать в зоне дорожных работ?", a: "Снизить скорость, следовать знакам, держать увеличенную дистанцию и не отвлекаться." },
    { q: "Что означает знак школьной зоны?", a: "Сниженную скорость и повышенную осторожность к пешеходам, когда зона активна." },
    { q: "Когда ремни безопасности обязательны?", a: "Для водителя и пассажиров в соответствии с законом штата; safest-практика — всегда пристегиваться." },
    { q: "Почему детям нужны подходящие автокресла/бустеры?", a: "Они обеспечивают правильную фиксацию и снижают риск травм." },
    { q: "Каков риск вождения в сонном состоянии?", a: "Снижение оценки ситуации и замедленная реакция, как при опьянении." },
    { q: "Что делать, если чувствуете сонливость за рулем?", a: "Безопасно остановиться и отдохнуть перед продолжением поездки." },
    { q: "Могут ли лекарства влиять на способность к вождению?", a: "Да; некоторые снижают внимательность, координацию или суждение." },
    { q: "Как связан законный возраст употребления алкоголя с лимитами DUI?", a: "Для несовершеннолетних водителей часто действуют более строгие нулевые/низкие лимиты BAC." },
    { q: "Что такое подразумеваемое согласие в законе DUI?", a: "Управляя авто, вы соглашаетесь на законное химическое тестирование; отказ влечет наказания." },
    { q: "Что делать, если светофоры не работают?", a: "Считать перекресток четырехсторонним STOP и проезжать осторожно." },
    { q: "Что означает знак использования полосы со стрелками?", a: "Из этой полосы разрешены только определенные маневры." },
    { q: "Как располагать авто для правого поворота?", a: "Подъезжайте по крайней правой практичной полосе и поворачивайте в ближайшую полосу, когда это законно." },
    { q: "Как располагать авто для левого поворота на двухсторонней дороге?", a: "Подъезжайте ближе к центральной линии и поворачивайте в соответствующую полосу, когда путь свободен." },
    { q: "При обгоне велосипедиста какое безопасное правило?", a: "Оставляйте достаточный боковой интервал и обгоняйте только когда это законно и безопасно." },
    { q: "Кто наиболее уязвим в дорожном движении?", a: "Пешеходы, велосипедисты и мотоциклисты." },
    { q: "Почему нельзя останавливаться на пешеходных переходах?", a: "Это блокирует приоритет пешеходов и обзор." },
    { q: "Что обычно означает треугольный красно-белый знак?", a: "Уступи дорогу." },
    { q: "Что обычно означает пятиугольный дорожный знак?", a: "Школьная зона или школьный переход." },
    { q: "Что сделать перед въездом на круговое движение?", a: "Уступить транспорту, уже движущемуся по кольцу." },
    { q: "Как подавать сигнал на круговом движении?", a: "Покажите сигнал выхода, когда готовитесь покинуть кольцо." },
    { q: "Какова цель тормозов ABS?", a: "Они помогают сохранять управляемость при интенсивном торможении." },
    { q: "Как тормозить с ABS?", a: "Нажмите сильно и удерживайте; не «качайте» педаль многократно." },
    { q: "Что делать, если заклинил акселератор?", a: "Переключить в нейтраль, безопасно рулить и тормозить до контролируемой остановки." },
    { q: "После мелкого ДТП без пострадавших что приоритетно?", a: "По возможности переместиться в безопасное место и обменяться обязательной информацией." },
    { q: "Какие документы водитель обычно должен иметь при себе?", a: "Действительные права, регистрацию и подтверждение страховки." },
    { q: "Что такое защитное (defensive) вождение?", a: "Предвидение опасностей и безопасные, законные решения для предотвращения аварий." },
    { q: "Почему зеркала нужно настроить до начала движения?", a: "Чтобы уменьшить слепые зоны и улучшить обзор ситуации." },
    { q: "Когда следует использовать аварийную сигнализацию?", a: "При аварии или неисправности авто, а не для обычной езды." },
    { q: "Что делать на нерегулируемом перекрестке?", a: "Снизить скорость, при необходимости уступить и ехать только когда безопасно." },
    { q: "Что означает разметка зоны запрета обгона?", a: "Не выезжать на встречную полосу для обгона." },
    { q: "Как действовать при желтой линии с одной прерывистой и одной сплошной стороной?", a: "Обгонять может только сторона с прерывистой линией, когда это безопасно." },
    { q: "Какой самый безопасный навык на зеленом сигнале?", a: "Посмотреть налево-направо-налево перед въездом на перекресток." },
    { q: "Почему скорость должна соответствовать условиям, а не только лимиту?", a: "Лимиты рассчитаны на идеальные условия; погода и трафик могут требовать меньшей скорости." },
    { q: "Что такое дисциплина движения по полосам?", a: "Держаться своей полосы и перестраиваться только при необходимости и безопасности." },
    { q: "Как реагировать на занос на льду?", a: "Смотрите туда, куда хотите ехать, и мягко рулите в этом направлении." },
    { q: "Что делать, если другой водитель включает поворотник, но не движется?", a: "Не предполагайте его намерение; ждите фактического движения и безопасного промежутка." },
    { q: "Что означает преимущество в движении на практике?", a: "Юридический приоритет проезда первым, но его нельзя навязывать небезопасно." },
    { q: "Почему опасно полагаться только на GPS?", a: "Дорожные знаки, условия и законные правила могут иметь приоритет над навигацией." },
    { q: "Какое ключевое правило рядом с пешеходами ночью?", a: "Снизить скорость и быть готовым немедленно остановиться." },
    { q: "Как проезжать мимо припаркованных машин экстренных или сервисных служб, когда этого требует закон?", a: "Перестройтесь, если безопасно, или значительно снизьте скорость, если смена полосы невозможна." }
  ],
  de: [
    { q: "Was bedeutet ein dauerhaft gelbes Ampellicht?", a: "Die Ampel schaltet gleich auf Rot; halten Sie sicher an, wenn möglich." },
    { q: "Was bedeutet ein grüner Pfeil an einer Kreuzung?", a: "Sie dürfen in Pfeilrichtung abbiegen und müssen dabei den rechtmäßig querenden Verkehr beachten." },
    { q: "Was bedeutet eine doppelte durchgezogene gelbe Mittellinie?", a: "Überholen ist in beide Richtungen verboten." },
    { q: "Was bedeutet eine unterbrochene weiße Linie zwischen Fahrstreifen?", a: "Fahrstreifenwechsel sind erlaubt, wenn es sicher ist." },
    { q: "Wann sollten Sie den toten Winkel prüfen?", a: "Vor jedem Fahrstreifenwechsel und Einfädeln." },
    { q: "Wie fädelt man am sichersten auf eine Autobahn ein?", a: "Beschleunigungsstreifen nutzen, Geschwindigkeit anpassen und bei ausreichender Lücke einfädeln." },
    { q: "Wenn Sie Ihre Ausfahrt verpassen, was tun Sie?", a: "Zur nächsten Ausfahrt weiterfahren und sicher neu routen." },
    { q: "Was tun an einem Vier-Wege-Stop?", a: "Das zuerst angehaltene Fahrzeug fährt zuerst; bei Gleichstand Vorfahrt für das Fahrzeug rechts." },
    { q: "Wer hat Vorfahrt beim Einfahren aus einer Grundstücksausfahrt?", a: "Der Verkehr auf der Straße und Fußgänger auf dem Gehweg." },
    { q: "Was sollten Sie vor dem Rückwärtsfahren tun?", a: "Alle Spiegel prüfen, über die Schulter schauen und langsam fahren." },
    { q: "Warum ist dichtes Auffahren gefährlich?", a: "Es lässt zu wenig Anhalteweg und erhöht das Risiko von Auffahrunfällen." },
    { q: "Wann sollten Sie den Folgeabstand über 3 Sekunden erhöhen?", a: "Bei Regen, Nebel, Schnee, Dunkelheit, dichtem Verkehr oder mit Anhänger." },
    { q: "Was bedeutet Aquaplaning?", a: "Die Reifen verlieren auf Wasser den Kontakt zur Fahrbahn." },
    { q: "Was tun, wenn Ihr Fahrzeug aquaplant?", a: "Gas wegnehmen, geradeaus lenken und starkes Bremsen vermeiden." },
    { q: "Welche Geschwindigkeit ist bei Nebel am sichersten?", a: "Eine reduzierte Geschwindigkeit, bei der Sie innerhalb der Sichtweite anhalten können." },
    { q: "Wann sollten Sie bei Fernlicht abblenden?", a: "Bei Gegenverkehr oder wenn Sie dicht hinter einem anderen Fahrzeug fahren." },
    { q: "Was tun, wenn nachts die Scheinwerfer ausfallen?", a: "Warnblinker einschalten, Geschwindigkeit reduzieren und sicher an den Rand fahren." },
    { q: "Wenn ein Reifen platzt: Was ist die erste Reaktion?", a: "Lenkrad festhalten, Gas wegnehmen und geradeaus lenken, bis das Fahrzeug kontrollierbar ist." },
    { q: "Was bedeutet ein roter Bordstein in der Regel?", a: "Halten, Stehen und Parken verboten." },
    { q: "Was bedeutet ein blauer Bordstein in der Regel?", a: "Parken nur für Inhaber eines Behindertenparkausweises." },
    { q: "Was tun, bevor Sie die Tür eines geparkten Autos zum Verkehr hin öffnen?", a: "Spiegel prüfen und über die Schulter nach Radfahrern und Fahrzeugen schauen." },
    { q: "Wie nah sollte man beim Parallelparken am Bordstein sein?", a: "So nah, dass der Verkehr nicht behindert wird, üblicherweise innerhalb einer kurzen gesetzlichen Distanz." },
    { q: "Beim Bergabparken mit Bordstein sollten die Räder zeigen:", a: "Zum Bordstein." },
    { q: "Beim Bergaufparken ohne Bordstein sollten die Räder zeigen:", a: "Zum Fahrbahnrand." },
    { q: "Was tun, wenn sich ein Rettungswagen mit Blaulicht und Sirene nähert?", a: "Vorfahrt gewähren, nach rechts fahren und sicher anhalten." },
    { q: "Dürfen Sie in eine Kreuzung einfahren, wenn Sie sie blockieren würden?", a: "Nein; nur einfahren, wenn Sie die Kreuzung vollständig räumen können." },
    { q: "Was ist ein häufiges Zeichen aggressiven Fahrens?", a: "Überhöhte Geschwindigkeit, ständiges Spurwechseln, dichtes Auffahren oder häufige unsichere Spurwechsel." },
    { q: "Wie reagieren Sie auf einen aggressiven Fahrer?", a: "Nicht einlassen; Abstand schaffen und vorbeilassen." },
    { q: "Warum sollten beide Hände am Lenkrad verfügbar sein?", a: "Das verbessert Kontrolle und Reaktion in Notfällen." },
    { q: "Was tun, bevor Sie links über Gegenverkehr abbiegen?", a: "Gegenverkehr und Fußgängern Vorrang geben und erst bei freier Lage abbiegen." },
    { q: "Was zeigt ein Andreaskreuz (railroad crossbuck) an?", a: "Bahnübergang voraus; auf Anhalten vorbereitet sein." },
    { q: "Wann müssen Sie an Bahngleisen anhalten?", a: "Bei blinkenden Signalen, geschlossenen Schranken, sichtbarem Zug oder wenn gesetzlich vorgeschrieben." },
    { q: "Wenn Ihr Fahrzeug auf Bahngleisen stehen bleibt, was tun Sie?", a: "Sofort aussteigen, sich von den Gleisen entfernen und den Notruf verständigen." },
    { q: "Wie hält man auf langen Gefällestrecken am sichersten die Geschwindigkeit?", a: "Niedrigeren Gang und kontrolliertes Bremsen nutzen, nicht dauerhaft stark auf die Bremse drücken." },
    { q: "Warum sind Baustellen besonders riskant?", a: "Spurverschwenkungen, Arbeiter in der Nähe, weniger Platz und plötzliche Verzögerungen." },
    { q: "Wie sollten Sie in einer Baustelle fahren?", a: "Langsamer fahren, Beschilderung folgen, mehr Abstand halten und Ablenkungen vermeiden." },
    { q: "Was bedeutet ein Schulzonen-Schild?", a: "Reduzierte Geschwindigkeit und erhöhte Fußgänger-Vorsicht, wenn die Zone aktiv ist." },
    { q: "Wann sind Sicherheitsgurte vorgeschrieben?", a: "Für Fahrer und Insassen gemäß Landesrecht; am sichersten ist immer anschnallen." },
    { q: "Warum sollten Kinder passende Kindersitze/Sitzerhöhungen nutzen?", a: "Sie sorgen für korrekte Rückhaltung und verringern das Verletzungsrisiko." },
    { q: "Was ist das Risiko von Fahren bei Müdigkeit?", a: "Beeinträchtigte Urteilsfähigkeit und verlangsamte Reaktion, ähnlich wie bei Alkohol." },
    { q: "Was tun, wenn Sie beim Fahren schläfrig werden?", a: "Sicher anhalten und ausruhen, bevor Sie weiterfahren." },
    { q: "Können Medikamente die Fahrtüchtigkeit beeinflussen?", a: "Ja; einige verringern Aufmerksamkeit, Koordination oder Urteilsvermögen." },
    { q: "Wie hängt das gesetzliche Trinkalter mit DUI-Grenzen zusammen?", a: "Für Minderjährige gelten oft strengere Null-/Niedrigtoleranz-Grenzen beim BAC." },
    { q: "Was bedeutet „implied consent“ im DUI-Recht?", a: "Durch das Fahren stimmen Sie rechtmäßigen chemischen Tests zu; Verweigerung wird sanktioniert." },
    { q: "Was tun, wenn Ampeln ausgefallen sind?", a: "Die Kreuzung wie einen All-Wege-Stop behandeln und vorsichtig fahren." },
    { q: "Was bedeutet ein Fahrstreifen-Steuerzeichen mit Pfeilen?", a: "Von diesem Fahrstreifen sind nur bestimmte Fahrmanöver erlaubt." },
    { q: "Wie positionieren Sie Ihr Fahrzeug für einen Rechtsabbieger?", a: "Im möglichst rechten Fahrstreifen anfahren und legal in den nächstgelegenen Fahrstreifen abbiegen." },
    { q: "Wie positionieren Sie Ihr Fahrzeug für einen Linksabbieger auf einer Zweirichtungsstraße?", a: "Nahe der Mittellinie anfahren und bei freier Lage in den richtigen Fahrstreifen abbiegen." },
    { q: "Welche sichere Regel gilt beim Überholen eines Radfahrers?", a: "Ausreichend Seitenabstand lassen und nur legal sowie sicher überholen." },
    { q: "Wer ist im Verkehr am verletzlichsten?", a: "Fußgänger, Radfahrer und Motorradfahrer." },
    { q: "Warum sollten Sie nicht auf Fußgängerüberwegen halten?", a: "Es blockiert das Vorrecht der Fußgänger und die Sichtlinien." },
    { q: "Was bedeutet ein dreieckiges rot-weißes Schild meist?", a: "Vorfahrt gewähren." },
    { q: "Was bedeutet ein fünfeckiges Verkehrszeichen meist?", a: "Schulzone oder Schulwegüberquerung." },
    { q: "Was tun vor dem Einfahren in einen Kreisverkehr?", a: "Dem Verkehr im Kreisverkehr Vorfahrt gewähren." },
    { q: "Wie signalisieren Sie im Kreisverkehr?", a: "Beim Verlassen den Blinker setzen." },
    { q: "Wozu dienen ABS-Bremsen?", a: "Sie helfen, bei starkem Bremsen die Lenkfähigkeit zu erhalten." },
    { q: "Wie bremst man mit ABS?", a: "Fest drücken und halten; nicht wiederholt pumpen." },
    { q: "Was tun, wenn das Gaspedal klemmt?", a: "In Neutral schalten, sicher lenken und kontrolliert abbremsen." },
    { q: "Nach einem leichten Unfall ohne Verletzte: Was hat Priorität?", a: "Wenn möglich an einen sicheren Ort fahren und die erforderlichen Daten austauschen." },
    { q: "Welche Dokumente sollten Fahrer grundsätzlich mitführen?", a: "Gültiger Führerschein, Zulassung und Versicherungsnachweis." },
    { q: "Was ist defensives Fahren?", a: "Gefahren voraussehen und sichere, legale Entscheidungen treffen, um Unfälle zu vermeiden." },
    { q: "Warum sollten Spiegel vor Fahrtantritt eingestellt werden?", a: "Um tote Winkel zu reduzieren und das Umfeld besser wahrzunehmen." },
    { q: "Wann sollten Warnblinker verwendet werden?", a: "Bei Notfällen oder liegengebliebenem Fahrzeug, nicht im normalen Fahrbetrieb." },
    { q: "Was tun an einer unkontrollierten Kreuzung?", a: "Geschwindigkeit reduzieren, bei Bedarf Vorfahrt gewähren und nur bei Sicherheit weiterfahren." },
    { q: "Was bedeutet eine Überholverbot-Markierung?", a: "Nicht zum Überholen in die Gegenfahrbahn fahren." },
    { q: "Wie verhalten Sie sich bei einer gelben Linie mit einer unterbrochenen und einer durchgezogenen Seite?", a: "Nur die Seite mit der unterbrochenen Linie darf bei Sicherheit überholen." },
    { q: "Was ist die sicherste Gewohnheit bei grünem Licht?", a: "Vor dem Einfahren links-rechts-links prüfen." },
    { q: "Warum sollte die Geschwindigkeit den Bedingungen und nicht nur dem Limit entsprechen?", a: "Tempolimits gehen von Idealbedingungen aus; Wetter/Verkehr können langsameres Fahren erfordern." },
    { q: "Was ist Spurdisziplin?", a: "In der eigenen Spur bleiben und nur bei Bedarf sowie sicher wechseln." },
    { q: "Wie reagieren Sie auf Glätte-Schleudern?", a: "Dorthin schauen, wo Sie hinwollen, und sanft in diese Richtung lenken." },
    { q: "Was tun, wenn ein anderer Fahrer blinkt, aber nicht fährt?", a: "Nicht auf die Absicht vertrauen; auf tatsächliche Bewegung und sichere Lücke warten." },
    { q: "Was bedeutet Vorfahrt in der Praxis?", a: "Der rechtliche Vorrang, zuerst zu fahren, aber niemals unsicher zu erzwingen." },
    { q: "Warum ist es unsicher, sich nur auf GPS zu verlassen?", a: "Verkehrszeichen, Bedingungen und Rechtsregeln können Navigationsanweisungen übersteuern." },
    { q: "Welche wichtige Regel gilt nachts in der Nähe von Fußgängern?", a: "Geschwindigkeit reduzieren und jederzeit sofort anhalten können." },
    { q: "Wie fahren Sie an abgestellten Einsatz- oder Servicefahrzeugen vorbei, wenn es gesetzlich vorgeschrieben ist?", a: "Wenn sicher, Spur wechseln; sonst deutlich verlangsamen, wenn Spurwechsel nicht möglich ist." }
  ],
  fr: [
    { q: "Que signifie un feu jaune fixe ?", a: "Le feu va passer au rouge; arrêtez-vous en sécurité si vous le pouvez." },
    { q: "Que signifie une flèche verte à une intersection ?", a: "Vous pouvez tourner dans le sens de la flèche en cédant au trafic transversal autorisé." },
    { q: "Que signifie une double ligne jaune continue au centre ?", a: "Dépassement interdit dans les deux sens." },
    { q: "Que signifie une ligne blanche discontinue entre les voies ?", a: "Le changement de voie est permis quand c’est sécuritaire." },
    { q: "Quand faut-il vérifier l’angle mort ?", a: "Avant chaque changement de voie et chaque insertion." },
    { q: "Quelle est la façon la plus sûre de s’insérer sur l’autoroute ?", a: "Utilisez la voie d’accélération, adaptez votre vitesse au trafic, puis insérez-vous lorsqu’il y a un espace." },
    { q: "Si vous ratez votre sortie, que devez-vous faire ?", a: "Continuez jusqu’à la sortie suivante et replanifiez en toute sécurité." },
    { q: "Que faire à un arrêt à quatre voies ?", a: "Le premier véhicule arrêté passe en premier; en cas d’égalité, cédez au véhicule à droite." },
    { q: "Qui a la priorité en sortant d’une entrée privée ?", a: "Le trafic déjà sur la route et les piétons sur le trottoir." },
    { q: "Que devez-vous faire avant de reculer ?", a: "Vérifier tous les rétroviseurs, regarder par-dessus l’épaule et avancer lentement." },
    { q: "Pourquoi coller le véhicule devant est-il dangereux ?", a: "Cela laisse trop peu de distance d’arrêt et augmente le risque de collision arrière." },
    { q: "Quand faut-il augmenter la distance de suivi au-delà de 3 secondes ?", a: "Sous la pluie, le brouillard, la neige, la nuit, en trafic dense ou en remorquage." },
    { q: "Que signifie l’aquaplanage ?", a: "Vos pneus perdent le contact avec la route à cause de l’eau." },
    { q: "Que faire si votre véhicule commence à aquaplaner ?", a: "Relâchez l’accélérateur, gardez la direction droite et évitez les freinages brusques." },
    { q: "Quelle est la vitesse la plus sûre dans le brouillard ?", a: "Une vitesse réduite qui permet de s’arrêter dans la distance visible." },
    { q: "Avec les feux de route, quand faut-il passer en feux de croisement ?", a: "À l’approche d’un véhicule en sens inverse ou en suivant de près un autre véhicule." },
    { q: "Que faire si vos phares tombent en panne la nuit ?", a: "Allumez les feux de détresse, ralentissez et rangez-vous en sécurité hors de la chaussée." },
    { q: "Si un pneu éclate, quelle est la première réaction ?", a: "Tenez fermement le volant, relâchez l’accélérateur et gardez la trajectoire jusqu’à reprendre le contrôle." },
    { q: "Qu’indique généralement un bord de trottoir rouge ?", a: "Interdiction de s’arrêter, de stationner à l’arrêt ou de se garer." },
    { q: "Qu’indique généralement un bord de trottoir bleu ?", a: "Stationnement réservé aux détenteurs d’un permis pour personnes handicapées." },
    { q: "Que faire avant d’ouvrir la portière d’une voiture stationnée vers la circulation ?", a: "Vérifier les rétroviseurs et regarder par-dessus l’épaule pour les cyclistes et véhicules." },
    { q: "En stationnement parallèle, à quelle distance du trottoir faut-il se placer ?", a: "Assez près pour ne pas gêner la circulation, généralement dans une courte distance légale." },
    { q: "En stationnement en descente avec trottoir, les roues doivent pointer :", a: "Vers le trottoir." },
    { q: "En stationnement en montée sans trottoir, les roues doivent pointer :", a: "Vers le bord de la route." },
    { q: "Que faire lorsqu’une ambulance approche avec feux et sirène ?", a: "Cédez le passage, rangez-vous à droite et arrêtez-vous quand c’est sécuritaire." },
    { q: "Peut-on entrer dans une intersection si on risque de la bloquer ?", a: "Non; n’entrez pas à moins de pouvoir la dégager." },
    { q: "Quel est un signe courant de conduite agressive ?", a: "Vitesse excessive, zigzags, conduite trop proche ou changements de voie dangereux fréquents." },
    { q: "Comment réagir face à un conducteur agressif ?", a: "N’engagez pas le conflit; créez de l’espace et laissez-le passer." },
    { q: "Pourquoi les deux mains doivent-elles rester disponibles sur le volant ?", a: "Cela améliore le contrôle et la réactivité en urgence." },
    { q: "Que faire avant de tourner à gauche en coupant la circulation ?", a: "Cédez aux véhicules venant en sens inverse et aux piétons, puis tournez quand la voie est libre." },
    { q: "Que signale une croix de passage à niveau (crossbuck) ?", a: "Un passage à niveau à venir; préparez-vous à vous arrêter." },
    { q: "Quand faut-il s’arrêter aux voies ferrées ?", a: "Quand les signaux clignotent, les barrières sont baissées, un train est visible ou la loi l’exige." },
    { q: "Si votre véhicule cale sur des rails, que devez-vous faire ?", a: "Sortez immédiatement et éloignez-vous des rails; appelez les services d’urgence." },
    { q: "Quelle est la façon la plus sûre de maîtriser la vitesse en longue descente ?", a: "Utilisez un rapport inférieur et un freinage contrôlé, pas une forte pression continue sur les freins." },
    { q: "Pourquoi les zones de travaux sont-elles à haut risque ?", a: "Déports de voie, travailleurs à proximité, espace réduit et ralentissements soudains." },
    { q: "Comment conduire dans une zone de travaux ?", a: "Ralentissez, suivez la signalisation, gardez plus de distance et évitez les distractions." },
    { q: "Qu’implique un panneau de zone scolaire ?", a: "Vitesse réduite et vigilance accrue envers les piétons lorsqu’il est en vigueur." },
    { q: "Quand la ceinture de sécurité est-elle obligatoire ?", a: "Pour conducteurs et passagers selon la loi de l’État; la pratique la plus sûre est de la porter toujours." },
    { q: "Pourquoi les enfants doivent-ils utiliser un siège auto/rehausseur adapté ?", a: "Il assure un bon ajustement de retenue et réduit le risque de blessure." },
    { q: "Quel est le risque de conduire en étant somnolent ?", a: "Jugement altéré et réaction retardée, semblables à l’intoxication." },
    { q: "Que faire si vous vous sentez somnolent au volant ?", a: "Arrêtez-vous en sécurité et reposez-vous avant de continuer." },
    { q: "Les médicaments peuvent-ils affecter la conduite ?", a: "Oui; certains réduisent la vigilance, la coordination ou le jugement." },
    { q: "Quel lien entre l’âge légal de consommation d’alcool et les limites DUI ?", a: "Les conducteurs mineurs ont souvent des limites BAC de tolérance zéro ou très basses." },
    { q: "Qu’est-ce que le consentement implicite en droit DUI ?", a: "En conduisant, vous consentez aux tests chimiques légaux; le refus entraîne des sanctions." },
    { q: "Que faire si les feux de circulation sont en panne ?", a: "Traitez l’intersection comme un arrêt toutes directions et avancez prudemment." },
    { q: "Que signifie un panneau de contrôle de voie avec flèches ?", a: "Seuls certains mouvements sont autorisés depuis cette voie." },
    { q: "Comment positionner votre véhicule pour tourner à droite ?", a: "Approchez par la voie la plus à droite praticable et tournez dans la voie la plus proche lorsque c’est légal." },
    { q: "Comment positionner votre véhicule pour tourner à gauche sur une route à double sens ?", a: "Approchez près de la ligne centrale et tournez dans la voie appropriée quand c’est dégagé." },
    { q: "En dépassant un cycliste, quelle est la règle de sécurité ?", a: "Laissez un espace latéral suffisant et dépassez seulement quand c’est légal et sécuritaire." },
    { q: "Qui est le plus vulnérable dans la circulation ?", a: "Les piétons, les cyclistes et les motocyclistes." },
    { q: "Pourquoi faut-il éviter de s’arrêter sur les passages piétons ?", a: "Cela bloque la priorité des piétons et les lignes de visibilité." },
    { q: "Que signifie généralement un panneau triangulaire rouge et blanc ?", a: "Cédez le passage." },
    { q: "Que signifie généralement un panneau routier en forme de pentagone ?", a: "Zone scolaire ou traversée scolaire." },
    { q: "Que faire avant d’entrer dans un carrefour giratoire ?", a: "Cédez au trafic déjà engagé dans le giratoire." },
    { q: "Comment signaler dans un giratoire ?", a: "Signalez votre sortie lorsque vous vous préparez à quitter le giratoire." },
    { q: "Quel est le rôle des freins ABS ?", a: "Ils aident à garder le contrôle de direction lors d’un freinage appuyé." },
    { q: "Comment freiner avec l’ABS ?", a: "Appuyez fermement et maintenez; ne pompez pas la pédale à répétition." },
    { q: "Que faire si l’accélérateur reste bloqué ?", a: "Passez au point mort, dirigez le véhicule en sécurité et freinez jusqu’à un arrêt contrôlé." },
    { q: "Après une collision mineure sans blessés, quelle est la priorité ?", a: "Se déplacer vers un endroit sûr si possible et échanger les informations requises." },
    { q: "Quels documents un conducteur doit-il généralement avoir avec lui ?", a: "Permis valide, immatriculation et preuve d’assurance." },
    { q: "Qu’est-ce que la conduite préventive (defensive) ?", a: "Anticiper les dangers et faire des choix sûrs et légaux pour éviter les collisions." },
    { q: "Pourquoi ajuster les rétroviseurs avant de conduire ?", a: "Pour réduire les angles morts et améliorer la conscience de l’environnement." },
    { q: "Quand utiliser les feux de détresse ?", a: "En cas d’urgence ou de véhicule immobilisé, pas pour la conduite normale." },
    { q: "Que faire à une intersection non contrôlée ?", a: "Ralentir, céder au besoin et avancer seulement quand c’est sécuritaire." },
    { q: "Que signifie un marquage de zone de non-dépassement ?", a: "Ne pas franchir vers la voie opposée pour dépasser." },
    { q: "Comment gérer une ligne jaune avec un côté discontinu et un côté continu ?", a: "Seul le côté avec ligne discontinue peut dépasser quand c’est sécuritaire." },
    { q: "Quelle est l’habitude la plus sûre au feu vert ?", a: "Balayer gauche-droite-gauche avant d’entrer dans l’intersection." },
    { q: "Pourquoi adapter la vitesse aux conditions et pas seulement aux limites ?", a: "Les limites supposent des conditions idéales; météo et trafic peuvent exiger de rouler plus lentement." },
    { q: "Qu’est-ce que la discipline de voie ?", a: "Rester dans sa voie et ne changer que lorsque nécessaire et sécuritaire." },
    { q: "Comment réagir à un dérapage sur glace ?", a: "Regardez où vous voulez aller et dirigez doucement dans cette direction." },
    { q: "Que faire si un autre conducteur met son clignotant mais ne bouge pas ?", a: "Ne supposez pas son intention; attendez un mouvement réel et un écart sécuritaire." },
    { q: "Que signifie la priorité de passage en pratique ?", a: "Le droit légal de passer d’abord, sans jamais l’imposer de façon dangereuse." },
    { q: "Pourquoi est-il risqué de se fier uniquement au GPS ?", a: "Les panneaux, les conditions et les règles légales peuvent primer sur l’itinéraire proposé." },
    { q: "Quelle règle clé près des piétons la nuit ?", a: "Réduire la vitesse et être prêt à s’arrêter immédiatement." },
    { q: "Comment dépasser des véhicules d’urgence ou de service stationnés lorsque la loi l’exige ?", a: "Changez de voie si c’est sécuritaire, ou ralentissez fortement si le changement de voie est impossible." }
  ]
};
